### ISSUE TITLE
Request to fix compilation error in warrior branch, Faced it while building raspberrypi image using poky (warrior branch).

### ISSUE THREAD

**Issue by thadivaka-gopikrishna** [WebPlatformForEmbedded/Thunder#212]
| FAILED: Source/compositorclient/Wayland/CMakeFiles/compositorclient.dir/Westeros.cpp.o
| /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ --sysroot=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/recipe-sysroot  -DBUILD_REFERENCE=367ca8bb390d960a6ba980b751db6b93fbb6b245 -DCORE_BLUETOOTH -DMESA_EGL_NO_X11_HEADERS -DNDEBUG -DPLATFORM_PC_UNIX=1 -DSYSTEM_PREFIX=OE -DWPEFRAMEWORK_WAYLAND_EGL_CLIENT -D__NO_WCHAR_SUPPORT__ -I/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/.. -I/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/core -I/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/core/.. -I/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/core/Source -mcpu=cortex-a53+crc -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0=/usr/src/debug/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0                      -fdebug-prefix-map=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0=/usr/src/debug/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0                      -fdebug-prefix-map=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/recipe-sysroot=                      -fdebug-prefix-map=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -mcpu=cortex-a53+crc -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/recipe-sysroot -DNDEBUG -fPIC   -std=c++11 -Wno-psabi -Wall -std=gnu++11 -MD -MT Source/compositorclient/Wayland/CMakeFiles/compositorclient.dir/Westeros.cpp.o -MF Source/compositorclient/Wayland/CMakeFiles/compositorclient.dir/Westeros.cpp.o.d -o Source/compositorclient/Wayland/CMakeFiles/compositorclient.dir/Westeros.cpp.o -c /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/Westeros.cpp
| In file included from /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/Westeros.cpp:13:
| /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/Implementation.h: In member function 'virtual EGLNativeWindowType WPEFramework::Wayland::Display::SurfaceImplementation::Native() const':
| /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/Implementation.h:119:65: error: invalid static_cast from type 'wl_egl_window* const' to type 'EGLNativeWindowType' {aka 'long unsigned int'}
|                  return (static_cast<EGLNativeWindowType>(_native));
|                                                                  ^
| /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/Westeros.cpp: In member function 'bool WPEFramework::Wayland::Display::SurfaceImplementation::Connect(void* const&)':
| /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/git/Source/compositorclient/Wayland/Westeros.cpp:653:65: error: invalid static_cast from type 'std::nullptr_t' to type 'EGLNativeWindowType' {aka 'long unsigned int'}
|                          static_cast<EGLNativeWindowType>(nullptr),
|                                                                  ^
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /disk/gopikrishna/raspberrypi/build/tmp/work/aarch64-poky-linux/wpeframework/3.0+gitAUTOINC+367ca8bb39-r0/temp/log.do_compile.23564)

**Comment by wouterlucas** [comment]
And the most constructive title of the year award goes to ^^
Please keep it civil friend, we're all human.

**Comment by thadivaka-gopikrishna** [comment]
Reopened to inform contributors the branch(warrior branch) where this issue was observed.

**Comment by wouterlucas** [comment]
I think this has to do with the RPI VC4Graphics vs dispmanx, can you try with dispmanx drivers on RPI Warrior branch?

**Comment by thadivaka-gopikrishna** [comment]
[bblayers.conf.txt](https://github.com/WebPlatformForEmbedded/Thunder/files/3630655/bblayers.conf.txt)
[local.conf.txt](https://github.com/WebPlatformForEmbedded/Thunder/files/3630656/local.conf.txt)

**Comment by pwielders** [comment]
We at metrological think that the compiler is our best friend. In a software development process it is good to find errors as soon as possible. See the V model of software development.
To detect erros as soon as possible in the code we promote defensive coding. A succefull compile with a segfault runs cost more money to resolve than having to tackle the issue at compile time.
Also we try to make our software as lean and mean ass possible. We are designing and running software on STB's which have very limited resources.
In light of this resource constrain X11 is *not* a candidate for embedded devices. Focus is on wayland, the light weight implementation of X11.
If you investigate the compile error you will find that the compiler is assuming that the definition of the EGLNativeWindowType is expecting a long unsigned int. 
If you look at the EGL definitions in the EGL header file:
https://www.khronos.org/registry/EGL/api/EGL/eglplatform.h
You will find that this happens if:
#elif defined(__unix__) || defined(USE_X11)

/* X11 (tentative)  */
#include <X11/Xlib.h>
#include <X11/Xutil.h>

typedef Display *EGLNativeDisplayType;
typedef Pixmap   EGLNativePixmapType;
typedef Window   EGLNativeWindowType;

the preprocessor finds that it is unix or X11 (interesting point to note here is that if it is linux, it is expecting to have X11 package installed, why ??)

However as stated above, we do not want to use X11, we want to use Wayland (embedded software, not a desktop)
So the preprocessor flag  WL_EGL_PLATFORM should be set.

#elif defined(WL_EGL_PLATFORM)

typedef struct wl_display     *EGLNativeDisplayType;
typedef struct wl_egl_pixmap  *EGLNativePixmapType;
typedef struct wl_egl_window  *EGLNativeWindowType;

In this case, the EGLNativeWindowType becomes a pointer again and the code will sucesfully compile.

This means that the compiler is warning us here for an incorrect system configuration, it is assuming X11, fow which we should not build. SO thank you compiler for this warning, we will check our build environment.

The body checking this in, builds in buildroot to test and validate. These environment are configured correctly and thus the issue did not surface, as we where building as the code is designed, without X11. I am not a Yocto expert and probably something is incorrect in the build of the WARRIOR BRANCH (don't know what it is) but please look at the build environment and make sure the EGL platform is proparly configured (so no X11). No code changes required here.

**Comment by wouterlucas** [comment]
You may want to try without vc4graphics by adding:
```
MACHINE_FEATURES_remove = "vc4graphics"
```

To your local configuration. Regardless we should move Yocto related discussions to `meta-wpe` and not in this repo.

**Comment by thadivaka-gopikrishna** [comment]
Thank you
Found the following in meta-wpe repository:

https://github.com/WebPlatformForEmbedded/meta-wpe/commit/4180987d3b36358684c1711dd7b5cc6bef77a402
